name: Build & Push Docker Image
on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: >
          ${{ secrets.DOCKERHUB_USERNAME }}/maibox:${{ github.sha }},
          ${{ secrets.DOCKERHUB_USERNAME }}/maibox:latest
